### ISSUE TITLE
Not picking up all TODO'S in comment and wrong line numbers.

### ISSUE THREAD

**Issue by KCarterSr** [mrlacey/WarnAboutTodos#5]
Here's an example of what I mean. Only two of the TODO's were picked up.
Thank you

![image](https://user-images.githubusercontent.com/2046991/51709522-97c0ff80-1ff4-11e9-8c57-c81354bf7391.png)

![image](https://user-images.githubusercontent.com/2046991/51709571-c4751700-1ff4-11e9-9456-323e3603e7f5.png)

**Comment by mrlacey** [comment]
@KCarterSr The ones that aren't being picked up are due to the fact that the default behavior is to only detect comments that start with "TODO"

To pick up all comments, regardless of where "TODO" appears in the line:
- create a file in the project called  **todo-warn.config**
- set its `BuildAction` to **AdditionalFiles**
- set the contents of the file to `[CONTAINS(TODO)]`

I'll investigate the line number issue.

**Comment by mrlacey** [comment]
Line number and column are specified for the comment as a whole.
That's why all the values are the same.

![image](https://user-images.githubusercontent.com/189547/51717421-a9c49180-2038-11e9-864d-4d96e066444a.png)

I hadn't considered comments that contain multiple TODO instructions. - _I just use single line comments for TODOs._

I guess the required change is for TODOs on multi-line comments to use the location of the TODO(s) on just that line, not the comment as a whole.

On a related note, should the **description** in the error list also be adjusted for TODOs that are in the middle of a line of text?
For instance, is `Initial coding by TODO AUTHOR` ok? or would `AUTHOR` be better?

**Comment by mrlacey** [comment]
This seems much better

![image](https://user-images.githubusercontent.com/189547/51719447-6ae70980-2041-11e9-8f59-5abe87f38484.png)

**Comment by KCarterSr** [comment]
I like Initial coding by TODO AUTHOR

Thanks

**Comment by mrlacey** [comment]
>           I like Initial coding by TODO AUTHOR
> Thanks

Good. Having seen both options I think this provides additional useful context.
